In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/content/train.csv")
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50

In [4]:
#a)
#here , firstly i'm Removing units so that the data gets correctly cleaned.
def extract_numeric(x):
    try:
        return float(str(x).split()[0].replace(',', ''))
    except:
        return None

df['Mileage'] = df['Mileage'].apply(extract_numeric)
df['Engine'] = df['Engine'].apply(lambda x: extract_numeric(str(x).replace('CC', '')))
df['Power'] = df['Power'].apply(lambda x: extract_numeric(str(x).replace('bhp', '')))
df['New_Price'] = df['New_Price'].astype(str)
df['New_Price'] = df['New_Price'].str.replace(' Lakh', '', regex=False)
df['New_Price'] = pd.to_numeric(df['New_Price'], errors='coerce')

In [5]:
#then working on missing value
df['Mileage'] = df['Mileage'].fillna(df['Mileage'].median())
df['Engine'] = df['Engine'].fillna(df['Engine'].median())
df['Power'] = df['Power'].fillna(df['Power'].median())
df['Seats'] = df['Seats'].fillna(df['Seats'].mode()[0])
df['New_Price'] = df['New_Price'].fillna(df['New_Price'].median())
df.dropna(inplace=True)
df.isnull().sum()

Unnamed: 0           0
Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
New_Price            0
Price                0
dtype: int64

Justification :
1.   To reduce the impact of outliers, the median is applied to numerical data.
2.  For categorical data, such as the number of seats, the mode is utilized.
3.  The last null rows are removed.

B)
Earlier completed in the previous section with str.replace and extract_numeric

In [6]:
#c)
df = pd.get_dummies(df, columns=['Fuel_Type', 'Transmission'], drop_first=True)
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582.0,126.20,5.0,11.665,12.50,False,False,True
1,2,Honda Jazz V,Chennai,2011,46000,First,13.00,1199.0,88.70,5.0,8.610,4.50,False,True,True
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248.0,88.76,7.0,11.665,6.00,False,False,True
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968.0,140.80,5.0,11.665,17.74,False,False,False
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461.0,63.10,5.0,11.665,3.50,False,False,True

In [ ]:
#d)
df['Car_Age'] = 2025 - df['Year']
df[['Year', 'Car_Age']].head()

In [7]:
#e)
selected_df = df[['Name', 'Location', 'Year', 'Mileage', 'Price']]
selected_df.head()

                               Name    Location  Year  Mileage  Price
0  Hyundai Creta 1.6 CRDi SX Option        Pune  2015    19.67  12.50
1                      Honda Jazz V     Chennai  2011    13.00   4.50
2                 Maruti Ertiga VDI     Chennai  2012    20.77   6.00
3   Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013    15.20  17.74
4            Nissan Micra Diesel XV      Jaipur  2013    23.08   3.50

In [8]:
high_mileage = df[df['Mileage'] > 20]
high_mileage.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248.0,88.76,7.0,11.665,6.00,False,False,True
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461.0,63.10,5.0,11.665,3.50,False,False,True
6,8,Volkswagen Vento Diesel Comfortline,Pune,2013,64430,First,20.54,1598.0,103.60,5.0,11.665,5.20,False,False,True
7,9,Tata Indica Vista Quadrajet LS,Chennai,2012,65932,Second,22.30,1248.0,74.00,5.0,11.665,1.95,False,False,True
8,10,Maruti Ciaz Zeta,Kochi,2018,25692,First,21.56,1462.0,103.25,5.0,10.650,9.95,False,True,True

In [9]:
df.rename(columns={'Price': 'Selling_Price'}, inplace=True)

In [10]:
sorted_df = df.sort_values(by='Selling_Price', ascending=False)
sorted_df[['Name', 'Selling_Price']].head()

                                             Name  Selling_Price
3952  Land Rover Range Rover 3.0 Diesel LWB Vogue         160.00
5620                   Lamborghini Gallardo Coupe         120.00
5752                       Jaguar F Type 5.0 V8 S         100.00
1457              Land Rover Range Rover Sport SE          97.07
1917                           BMW 7 Series 740Li          93.67

In [11]:
grouped = df.groupby('Location')['Selling_Price'].mean().reset_index()
grouped.rename(columns={'Selling_Price': 'Average_Price'}, inplace=True)
grouped.head()

     Location  Average_Price
0   Ahmedabad       8.567248
1   Bangalore      13.482670
2     Chennai       7.958340
3  Coimbatore      15.160206
4       Delhi       9.881944

In [12]:
df.to_csv("cleaned_used_cars.csv", index=False)